[package]
name = "acvm-backend-plonky2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acvm = "0.27.0"
clap = "4.4.7"
